### PR TITLE
Customizer global card style

### LINKED ISSUE #60: Explore global settings for cards
<a href="https://github.com/jauyong"></img></a> **Issue by [jauyong](https://github.com/jauyong)**
_Monday Dec 07, 2020 at 14:26 GMT_
_Originally opened as https://github.com/xwp/material-design-wp-plugin/issues/463_

----

## Feature description

Add options in the Customizer for global settings for cards (elevated and outlined).

This ticket was split from #362 
Note: there was a similar discussion regarding round corners.
Question: What about theme options that cover the same settings?
Note: Design may be needed here.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Add toggle for all cards: Outlined or filled
2. Any card field should follow the guideline set above, unless a user has specifically chosen something at the block level. 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

### PR DESCRIPTION
**Pull request by PatelUtkarsh**
## Summary
- Adds inherit from global option for card elevation. (Addition to elevated and outlined).
- Adds global style setting in customizer with elevated and outlined option with reset button.
- Reset button searches post with outlined or elevated preference and resets it to global.
- When global elevation is selected in card block setting, it will take preference from the customizer.

https://user-images.githubusercontent.com/5015489/136013660-9e5fd870-5e7f-4df0-8b4a-b85bd0ca35ea.mp4

Fixes #60 

## Checklist

- [ ] My pull request is addressing an [open issue](https://github.com/material-components/material-design-for-wordpress/issues) (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/material-components/material-design-for-wordpress/blob/main/contributing/engineering.md#tests).
- [ ] My code follows the [Contributing Guidelines](https://github.com/material-components/material-design-for-wordpress/blob/main/contributing.md) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by emeaguiar** [comment]
@PatelUtkarsh #211 Was the first one I was able to merge. Is I figured there's some conflicts that need to be resolved in order to merge this one

**Comment by PatelUtkarsh** [comment]
@emeaguiar Thanks, I will take a look and resolve.

**Comment by PatelUtkarsh** [comment]
@emeaguiar This PR is ready for review.

**Review by emeaguiar — APPROVED** [review]
👍

**Pull request merged**
