### PR TITLE
Fix block.json path

### PR DESCRIPTION
**Pull request by PatelUtkarsh**
## Summary

Fixes #

## Checklist

- [ ] My pull request is addressing an [open issue](https://github.com/material-components/material-design-for-wordpress/issues) (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/material-components/material-design-for-wordpress/blob/main/contributing/engineering.md#tests).
- [ ] My code follows the [Contributing Guidelines](https://github.com/material-components/material-design-for-wordpress/blob/main/contributing.md) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by PatelUtkarsh** [comment]
Hello @rodydavis, We can just release plugin with 0.6.1 and skip theme since there are no changes on theme.

**Review by rodydavis — APPROVED** [review]
LGTM

**Comment by PatelUtkarsh** [comment]
Thanks @rodydavis, Can you do WP.org plugin release after merging this PR?

**Review by rodydavis — APPROVED** [review]
LGTM

**Pull request merged**
